# site configuration

theme: jekyll-theme-minimal

lang: en

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# main title
title: Alex Dateling

# subtitle
tagline: Blog

# used by seo meta and the atom feed
description: Life of Alex Dateling